name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Set up Haxe
        uses: krdlab/setup-haxe@v1.5.1
        with:
          haxe-version: 4.2.5

      - name: Install dependencies
        run: |
          # Update haxelib
          haxelib --global update haxelib 

          # hxcpp
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git v4.3.10 --always  --quiet
          pushd .
          cd /usr/local/lib/haxe/lib/hxcpp/git/tools/hxcpp
          haxe compile.hxml
          popd

          # lime
          git clone --recursive --depth 1 --branch 8.1.0-Dev https://github.com/openfl/lime
          haxelib dev lime lime

          # format
          haxelib install format --quiet

          # hxp
          haxelib install hxp --quiet

      - name: Run my action
        uses: ./